# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service/user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_service/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17user_service/user.proto\x12\nservice.v1\x1a\x13\x63ommon/common.proto\"L\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"F\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t2\x8c\x01\n\x0bUserService\x12\x44\n\nCreateUser\x12\x1d.service.v1.CreateUserRequest\x1a\x17.common.v1.BaseResponse\x12\x37\n\x07GetUser\x12\x1a.service.v1.GetUserRequest\x1a\x10.service.v1.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=60
  _globals['_USER']._serialized_end=136
  _globals['_CREATEUSERREQUEST']._serialized_start=138
  _globals['_CREATEUSERREQUEST']._serialized_end=208
  _globals['_GETUSERREQUEST']._serialized_start=210
  _globals['_GETUSERREQUEST']._serialized_end=243
  _globals['_USERSERVICE']._serialized_start=246
  _globals['_USERSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
