name: Proto CI

on:
  push:
    paths:
      - 'protos/**'
      - 'scripts/gen_proto.py'
      - '.github/workflows/proto-ci.yml'
  pull_request:
    paths:
      - 'protos/**'
      - 'scripts/gen_proto.py'

jobs:
  proto-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
        uv pip install -r requirements-dev.txt

    - name: Generate Proto code
      run: python scripts/gen_proto.py

    - name: Type check generated code
      run: mypy services/

    - name: Run proto tests
      run: pytest tests/
